### ISSUE TITLE
Support pkg-local custom options in `ido.pkg.setup`

### ISSUE THREAD

**Issue by alexanderjeurissen** [ido-nvim/core#20]
As can be seen in the readme of `ido-git`: https://github.com/ido-nvim/ido-git/blob/main/README.md

and as referenced in the following issues:
- https://github.com/ido-nvim/ido-git/issues/2
- https://github.com/ido-nvim/files/issues/3

Currently there is no way to pass `custom` options using `ido.pkg.setup`

It would really help extensibility if `ido-pkg` authors could access custom options that get passed in the setup function. This could easily be achieved by adding a additional key to the opts in `ido.pkg.setup`:

```markdown
# pkg.setup(NAME, OPTS)

Configure an existing package. It will change the options related to the package

name The name of the package

opts The table of options related to the package except disable and main. See Package structure above.

**pkg_opts A table of options shared with the package for internal configuration**

If a package with that name does not exist, it will throw an error.
```

which would simplify `ido-git` configuration to:

```lua
ido.pkg.setup('git-diff', {
  pkg_opts = {
    COMMAND = 'git diff master --name-only
  }
})
```

I envision the `pkg_opts` would then be passed as an argument to the main entry point of the package e.g.

```lua
pkg.new("git_diff", {
   main = function(pkg_opts)
       -- do stuff with pkg_opts 
   end,
   bind = {
      -- Bind it to <Leader>gf
      key = "<Leader>gd",
      mode = "n",
      noremap = true,
      silent = true,
      buffer = false,
   },
})
```

**Comment by shoumodip** [comment]
Merged in #21. Closing this
